<!doctype html>
<html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"><meta><title>三类块操作 - 李浩的博客</title><link rel="manifest" href="/manifest.json"><meta name="application-name" content="李浩"><meta name="msapplication-TileImage" content="/img/favicon.svg"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="李浩"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="description" content="块在AutoCAD中扮演着重要角色，它可以把多个图形组成一个整体，起到组织图形层次和图元复用的作用。 AutoCAD中有三种类型的块：普通快、动态属性块（可根据属性值修改图形尺寸）、增强属性块（在块中添加文字动态属性），后面两种在第一种的基础上添加了个性化功能。 本文针对这三类块封装若干二次开发接口。"><meta property="og:type" content="blog"><meta property="og:title" content="三类块操作"><meta property="og:url" content="http://example.com/post/75d48c9978ad/"><meta property="og:site_name" content="李浩的博客"><meta property="og:description" content="块在AutoCAD中扮演着重要角色，它可以把多个图形组成一个整体，起到组织图形层次和图元复用的作用。 AutoCAD中有三种类型的块：普通快、动态属性块（可根据属性值修改图形尺寸）、增强属性块（在块中添加文字动态属性），后面两种在第一种的基础上添加了个性化功能。 本文针对这三类块封装若干二次开发接口。"><meta property="og:locale" content="zh_CN"><meta property="og:image" content="http://example.com/img/og_image.png"><meta property="article:published_time" content="2024-07-07T08:02:04.000Z"><meta property="article:modified_time" content="2024-07-07T13:17:03.635Z"><meta property="article:author" content="李浩"><meta property="twitter:card" content="summary"><meta property="twitter:image:src" content="http://example.com/img/og_image.png"><script type="application/ld+json">{"@context":"https://schema.org","@type":"BlogPosting","mainEntityOfPage":{"@type":"WebPage","@id":"http://example.com/post/75d48c9978ad/"},"headline":"三类块操作","image":["http://example.com/img/og_image.png"],"datePublished":"2024-07-07T08:02:04.000Z","dateModified":"2024-07-07T13:17:03.635Z","author":{"@type":"Person","name":"李浩"},"publisher":{"@type":"Organization","name":"李浩的博客","logo":{"@type":"ImageObject","url":"http://example.com/img/logo.svg"}},"description":"块在AutoCAD中扮演着重要角色，它可以把多个图形组成一个整体，起到组织图形层次和图元复用的作用。 AutoCAD中有三种类型的块：普通快、动态属性块（可根据属性值修改图形尺寸）、增强属性块（在块中添加文字动态属性），后面两种在第一种的基础上添加了个性化功能。 本文针对这三类块封装若干二次开发接口。"}</script><link rel="canonical" href="http://example.com/post/75d48c9978ad/"><link rel="icon" href="/img/favicon.svg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@11.7.0/styles/github.css"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;600&amp;family=Source+Code+Pro"><link rel="stylesheet" href="/css/default.css"><style>body>.footer,body>.navbar,body>.section{opacity:0}</style><!--!--><!--!--><!--!--><script src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js" defer></script><!--!--><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cookieconsent@3.1.1/build/cookieconsent.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lightgallery@1.10.0/dist/css/lightgallery.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/justifiedGallery@3.8.1/dist/css/justifiedGallery.min.css"><!--!--><!--!--><!--!--><style>.pace{-webkit-pointer-events:none;pointer-events:none;-webkit-user-select:none;-moz-user-select:none;user-select:none}.pace-inactive{display:none}.pace .pace-progress{background:#3273dc;position:fixed;z-index:2000;top:0;right:100%;width:100%;height:2px}</style><script src="https://cdn.jsdelivr.net/npm/pace-js@1.2.4/pace.min.js"></script><!--!--><!--!--><!-- hexo injector head_end start --><script>
  (function () {
      function switchTab() {
          if (!location.hash) {
            return;
          }

          const id = '#' + CSS.escape(location.hash.substring(1));
          const $tabMenu = document.querySelector(`.tabs a[href="${id}"]`);
          if (!$tabMenu) {
            return;
          }

          const $tabMenuContainer = $tabMenu.parentElement.parentElement;
          Array.from($tabMenuContainer.children).forEach($menu => $menu.classList.remove('is-active'));
          Array.from($tabMenuContainer.querySelectorAll('a'))
              .map($menu => document.getElementById($menu.getAttribute("href").substring(1)))
              .forEach($content => $content.classList.add('is-hidden'));

          if ($tabMenu) {
              $tabMenu.parentElement.classList.add('is-active');
          }
          const $activeTab = document.querySelector(id);
          if ($activeTab) {
              $activeTab.classList.remove('is-hidden');
          }
      }
      switchTab();
      window.addEventListener('hashchange', switchTab, false);
  })();
  </script><!-- hexo injector head_end end --><meta name="generator" content="Hexo 7.2.0"></head><body class="is-2-column"><nav class="navbar navbar-main"><div class="container navbar-container"><div class="navbar-brand justify-content-center"><a class="navbar-item navbar-logo" href="/"><img src="/img/logo.svg" alt="李浩的博客" height="28"></a></div><div class="navbar-menu"><div class="navbar-start"><a class="navbar-item" href="/">主页</a><a class="navbar-item" href="/categories">分类</a><a class="navbar-item" href="/categories/%E9%9A%8F%E7%AC%94">随笔</a><a class="navbar-item" href="/categories/%E3%80%90%E5%BA%95%E5%B1%82%E3%80%91">【底层】</a><a class="navbar-item" href="/categories/%E3%80%90%E7%AE%97%E6%B3%95%E3%80%91">【算法】</a><a class="navbar-item" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91">【工程】</a><a class="navbar-item" href="/categories/%E3%80%90%E6%9E%B6%E6%9E%84%E3%80%91">【架构】</a><a class="navbar-item" href="/link">链接</a><a class="navbar-item" href="/about">关于</a></div><div class="navbar-end"><a class="navbar-item is-hidden-tablet catalogue" title="目录" href="javascript:;"><i class="fas fa-list-ul"></i></a><a class="navbar-item search" title="搜索" href="javascript:;"><i class="fas fa-search"></i></a></div></div></div></nav><section class="section"><div class="container"><div class="columns"><div class="column order-2 column-main is-8-tablet is-9-desktop is-9-widescreen"><div class="card"><article class="card-content article" role="article"><div class="article-meta is-size-7 is-uppercase level is-mobile"><div class="level-left"><span class="level-item"><time dateTime="2024-07-07T08:02:04.000Z" title="2024/7/7 16:02:04">2024-07-07</time>发表</span><span class="level-item"><time dateTime="2024-07-07T13:17:03.635Z" title="2024/7/7 21:17:03">2024-07-07</time>更新</span><span class="level-item"><a class="link-muted" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/">【工程】</a><span> / </span><a class="link-muted" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/CAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91/">CAD二次开发</a></span><span class="level-item" id="busuanzi_container_page_pv"><span id="busuanzi_value_page_pv">0</span>次访问</span></div></div><h1 class="title is-3 is-size-4-mobile">三类块操作</h1><div class="content"><p>块在AutoCAD中扮演着重要角色，它可以把多个图形组成一个整体，起到组织图形层次和图元复用的作用。<br>
AutoCAD中有三种类型的块：普通快、动态属性块（可根据属性值修改图形尺寸）、增强属性块（在块中添加文字动态属性），后面两种在第一种的基础上添加了个性化功能。<br>
本文针对这三类块封装若干二次开发接口。</p>
<span id="more"></span>
<h1 id="普通块"><a class="markdownIt-Anchor" href="#普通块"></a> 普通块</h1>
<ul>
<li>AddBlockTableRecord：添加块定义（块参照的模板）</li>
<li>InsertBlockReference：添加块参照</li>
<li>RemoveBlockRefrences：根据块定义名删除块参照</li>
<li>GetBlockReferenceByName：根据块定义名获取所有块参照</li>
<li>GetEntitiesInBlockReference：获取块参照中的所有实体（考虑块的深度遍历）</li>
<li>GetPointInTotalSystem：获取块参照中某点（块参照的局部坐标系）的全局坐标</li>
</ul>
<figure class="highlight cs"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br><span class="line">91</span><br><span class="line">92</span><br><span class="line">93</span><br><span class="line">94</span><br><span class="line">95</span><br><span class="line">96</span><br><span class="line">97</span><br><span class="line">98</span><br><span class="line">99</span><br><span class="line">100</span><br><span class="line">101</span><br><span class="line">102</span><br><span class="line">103</span><br><span class="line">104</span><br><span class="line">105</span><br><span class="line">106</span><br><span class="line">107</span><br><span class="line">108</span><br><span class="line">109</span><br><span class="line">110</span><br><span class="line">111</span><br><span class="line">112</span><br><span class="line">113</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> ObjectId <span class="title">AddBlockTableRecord</span>(<span class="params">Document doc, <span class="built_in">string</span> blockName, List&lt;ObjectId&gt; ents</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Database db = doc.Database;</span><br><span class="line">    ObjectId resId = ObjectId.Null;</span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = db.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        BlockTable bt = db.BlockTableId.GetObject(OpenMode.ForWrite) <span class="keyword">as</span> BlockTable;</span><br><span class="line">        <span class="keyword">if</span> (bt.Has(blockName))</span><br><span class="line">            doc.RemoveBlockDefinition(blockName);</span><br><span class="line">        BlockTableRecord btr = <span class="keyword">new</span> BlockTableRecord();</span><br><span class="line">        btr.Name = blockName;</span><br><span class="line">        resId = bt.Add(btr);</span><br><span class="line">        transaction.AddNewlyCreatedDBObject(btr, <span class="literal">true</span>);</span><br><span class="line">        ObjectIdCollection collection = <span class="keyword">new</span> ObjectIdCollection(ents.ToArray());</span><br><span class="line">        IdMapping mapping = <span class="keyword">new</span> IdMapping();</span><br><span class="line">        db.DeepCloneObjects(collection, resId, mapping, <span class="literal">false</span>);</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> resId;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> ObjectId <span class="title">InsertBlockReference</span>(<span class="params">Database db, <span class="built_in">string</span> blockName, Point3d position, Scale3d scale, <span class="built_in">double</span> rotateAngle</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ObjectId blockReferenceId;</span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = db.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        BlockTable blockTable = db.BlockTableId.GetObject(OpenMode.ForWrite) <span class="keyword">as</span> BlockTable;</span><br><span class="line">        <span class="keyword">if</span> (!blockTable.Has(blockName)) <span class="keyword">return</span> ObjectId.Null;</span><br><span class="line">        BlockTableRecord blockTableRecord = transaction.GetObject(blockTable[BlockTableRecord.ModelSpace], OpenMode.ForWrite) <span class="keyword">as</span> BlockTableRecord;</span><br><span class="line">        BlockReference blockReference = <span class="keyword">new</span> BlockReference(position, blockTable[blockName]);</span><br><span class="line">        blockReference.ScaleFactors = scale;</span><br><span class="line">        blockReference.Rotation = rotateAngle;</span><br><span class="line">        blockReferenceId = blockTableRecord.AppendEntity(blockReference);</span><br><span class="line">        transaction.AddNewlyCreatedDBObject(blockReference, <span class="literal">true</span>);</span><br><span class="line">        blockTable.DowngradeOpen();</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> blockReferenceId;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">RemoveBlockRefrences</span>(<span class="params"><span class="keyword">this</span> Document doc, <span class="built_in">string</span> name</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    List&lt;BlockReference&gt; blocks = GetBlockReferenceByName(doc, name);</span><br><span class="line">    ObjectId[] objectIds = <span class="keyword">new</span> ObjectId[blocks.Count];</span><br><span class="line">    <span class="keyword">for</span> (<span class="built_in">int</span> i = <span class="number">0</span>; i &lt; blocks.Count; i++)</span><br><span class="line">    &#123;</span><br><span class="line">        BlockReference block = blocks[i];</span><br><span class="line">        objectIds[i] = block.ObjectId;</span><br><span class="line">    &#125;</span><br><span class="line">    DwgPainter.DeleteEntities(doc.Database, objectIds);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> List&lt;BlockReference&gt; <span class="title">GetBlockReferenceByName</span>(<span class="params"><span class="keyword">this</span> Document doc, <span class="built_in">string</span> name</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    List&lt;BlockReference&gt; blockReferences = <span class="keyword">new</span> List&lt;BlockReference&gt;();</span><br><span class="line">    Database db = doc.Database;</span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = doc.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        BlockTable bt = transaction.GetObject(db.BlockTableId, OpenMode.ForRead) <span class="keyword">as</span> BlockTable;</span><br><span class="line">        BlockTableRecord btr = transaction.GetObject(bt[BlockTableRecord.ModelSpace], OpenMode.ForRead) <span class="keyword">as</span> BlockTableRecord;</span><br><span class="line">        <span class="keyword">foreach</span> (ObjectId id <span class="keyword">in</span> btr)</span><br><span class="line">        &#123;</span><br><span class="line">            Entity entity = transaction.GetObject(id, OpenMode.ForRead) <span class="keyword">as</span> Entity;</span><br><span class="line">            <span class="keyword">if</span> (entity <span class="keyword">is</span> BlockReference &amp;&amp; (entity <span class="keyword">as</span> BlockReference).Name == name)</span><br><span class="line">            &#123;</span><br><span class="line">                blockReferences.Add(entity <span class="keyword">as</span> BlockReference);</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> blockReferences;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> List&lt;Entity&gt; <span class="title">GetEntitiesInBlockReference</span>(<span class="params">BlockReference block</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">if</span> (block == <span class="literal">null</span>) <span class="keyword">return</span> <span class="literal">null</span>;</span><br><span class="line">    List&lt;Entity&gt; entities = <span class="keyword">new</span> List&lt;Entity&gt;();</span><br><span class="line">    Queue&lt;BlockReference&gt; blocks = <span class="keyword">new</span> Queue&lt;BlockReference&gt;();</span><br><span class="line">    blocks.Enqueue(block);</span><br><span class="line">    <span class="keyword">while</span> (blocks.Count &gt; <span class="number">0</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        BlockReference blockReference = blocks.Dequeue();</span><br><span class="line">        DBObjectCollection objects = <span class="keyword">new</span> DBObjectCollection();</span><br><span class="line">        blockReference.Explode(objects);</span><br><span class="line">        <span class="keyword">foreach</span> (<span class="keyword">var</span> obj <span class="keyword">in</span> objects)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">if</span> (obj <span class="keyword">is</span> BlockReference)</span><br><span class="line">                blocks.Enqueue(obj <span class="keyword">as</span> BlockReference);</span><br><span class="line">            <span class="keyword">else</span> <span class="keyword">if</span> (obj <span class="keyword">is</span> Line || obj <span class="keyword">is</span> Polyline || obj <span class="keyword">is</span> Circle || obj <span class="keyword">is</span> Arc || obj <span class="keyword">is</span> Polyline2d)</span><br><span class="line">                entities.Add(obj <span class="keyword">as</span> Entity);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> entities;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="built_in">bool</span> <span class="title">GetPointInTotalSystem</span>(<span class="params">BlockReference reference, Point3d pointInLocalSystem, <span class="keyword">out</span> Point3d pointInTotalSystem</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    pointInTotalSystem = Point3d.Origin;</span><br><span class="line">    <span class="keyword">if</span> (reference == <span class="literal">null</span>)</span><br><span class="line">        <span class="keyword">return</span> <span class="literal">false</span>;</span><br><span class="line">    Point3d insertPoint = reference.Position;</span><br><span class="line">    <span class="built_in">double</span> factor = reference.ScaleFactors.X;</span><br><span class="line">    <span class="built_in">double</span> angle = reference.Rotation;</span><br><span class="line">    <span class="built_in">double</span> dist = Math.Sqrt(pointInLocalSystem.X * pointInLocalSystem.X + pointInLocalSystem.Y * pointInLocalSystem.Y) * factor;</span><br><span class="line">    <span class="built_in">double</span> angleDefiniton = DwgPainter.Arctan(pointInLocalSystem.Y, pointInLocalSystem.X);</span><br><span class="line">    angle += angleDefiniton;</span><br><span class="line">    <span class="keyword">if</span> (angle &gt; Math.PI * <span class="number">2</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        angle -= Math.PI * <span class="number">2</span>;</span><br><span class="line">    &#125;</span><br><span class="line">    pointInTotalSystem = <span class="keyword">new</span> Point3d(insertPoint.X + dist * Math.Cos(angle), insertPoint.Y + dist * Math.Sin(angle), <span class="number">0</span>);</span><br><span class="line">    <span class="keyword">return</span> <span class="literal">true</span>;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h1 id="动态属性块"><a class="markdownIt-Anchor" href="#动态属性块"></a> 动态属性块</h1>
<ul>
<li>普通快的所有方法也适用于动态属性块</li>
<li>GetDynamicBlockPropertyValue：获取某一实体的某一属性值</li>
<li>SetDynamicBlockDistance：设置某一实体某一属性的值（值类型为距离）</li>
<li>SetDynamicBlockPropertyValue：设置某一实体某一属性的值（值类型为距离）</li>
</ul>
<figure class="highlight cs"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> Object <span class="title">GetDynamicBlockPropertyValue</span>(<span class="params"><span class="keyword">this</span> ObjectId id, <span class="built_in">string</span> propertyName</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Database db = id.Database;</span><br><span class="line">    <span class="built_in">object</span> <span class="keyword">value</span> = <span class="literal">null</span>;</span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = db.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        Entity entity = transaction.GetObject(id, OpenMode.ForRead) <span class="keyword">as</span> Entity;</span><br><span class="line">        <span class="keyword">if</span> (entity <span class="keyword">is</span> BlockReference &amp;&amp; (entity <span class="keyword">as</span> BlockReference).IsDynamicBlock)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">var</span> props = (entity <span class="keyword">as</span> BlockReference).DynamicBlockReferencePropertyCollection;</span><br><span class="line">            <span class="keyword">foreach</span> (DynamicBlockReferenceProperty prop <span class="keyword">in</span> props)</span><br><span class="line">                <span class="keyword">if</span> (prop.PropertyName == propertyName)</span><br><span class="line">                    <span class="keyword">value</span> = prop.Value;</span><br><span class="line">        &#125;</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> <span class="keyword">value</span>;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">SetDynamicBlockDistance</span>(<span class="params"><span class="keyword">this</span> ObjectId id,<span class="built_in">string</span> propertyName, <span class="built_in">double</span> distance</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Database db = id.Database;</span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = db.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        Entity entity = transaction.GetObject(id, OpenMode.ForWrite) <span class="keyword">as</span> Entity;</span><br><span class="line">        <span class="keyword">if</span> (entity <span class="keyword">is</span> BlockReference &amp;&amp; (entity <span class="keyword">as</span> BlockReference).IsDynamicBlock)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">var</span> props = (entity <span class="keyword">as</span> BlockReference).DynamicBlockReferencePropertyCollection;</span><br><span class="line">            <span class="keyword">foreach</span> (DynamicBlockReferenceProperty prop <span class="keyword">in</span> props)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">if</span> (!prop.ReadOnly &amp;&amp; prop.PropertyName == propertyName</span><br><span class="line">                    &amp;&amp; prop.UnitsType == DynamicBlockReferencePropertyUnitsType.Distance)</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="built_in">object</span> val = distance;</span><br><span class="line">                    prop.Value = val;</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">SetDynamicBlockPropertyValue</span>(<span class="params"><span class="keyword">this</span> ObjectId id, <span class="built_in">string</span> propertyName, <span class="built_in">string</span> <span class="keyword">value</span></span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Database db = id.Database;</span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = db.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        Entity entity = transaction.GetObject(id, OpenMode.ForWrite) <span class="keyword">as</span> Entity;</span><br><span class="line">        <span class="keyword">if</span> (entity <span class="keyword">is</span> BlockReference &amp;&amp; (entity <span class="keyword">as</span> BlockReference).IsDynamicBlock)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">var</span> props = (entity <span class="keyword">as</span> BlockReference).DynamicBlockReferencePropertyCollection;</span><br><span class="line">            <span class="keyword">foreach</span> (DynamicBlockReferenceProperty prop <span class="keyword">in</span> props)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">if</span> (!prop.ReadOnly &amp;&amp; prop.PropertyName == propertyName</span><br><span class="line">                    &amp;&amp; prop.UnitsType == DynamicBlockReferencePropertyUnitsType.NoUnits)</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="built_in">object</span> val = <span class="keyword">value</span>;</span><br><span class="line">                    prop.Value = val;</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h1 id="增强属性块"><a class="markdownIt-Anchor" href="#增强属性块"></a> 增强属性块</h1>
<ul>
<li>普通快的所有方法也适用于增强属性块</li>
<li>InsertBlockWithAttribute：插入增强属性块的同时并设置其中的文字（必须设置，不然增强属性文字会消失，后续无法修改）</li>
<li>ChangeBlockAttributes：修改增强属性块中的文字</li>
<li>ChangeBlockAttributesColor：修改块中增强文字的颜色</li>
</ul>
<figure class="highlight cs"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br><span class="line">91</span><br><span class="line">92</span><br><span class="line">93</span><br><span class="line">94</span><br><span class="line">95</span><br><span class="line">96</span><br><span class="line">97</span><br><span class="line">98</span><br><span class="line">99</span><br><span class="line">100</span><br><span class="line">101</span><br><span class="line">102</span><br><span class="line">103</span><br><span class="line">104</span><br><span class="line">105</span><br><span class="line">106</span><br><span class="line">107</span><br><span class="line">108</span><br><span class="line">109</span><br><span class="line">110</span><br><span class="line">111</span><br><span class="line">112</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> ObjectId <span class="title">InsertBlockWithAttribute</span>(<span class="params"><span class="keyword">this</span> Document doc, <span class="built_in">string</span> blockName, Point3d insertPoint,<span class="built_in">string</span> layerName, Dictionary&lt;<span class="built_in">string</span>, <span class="built_in">string</span>&gt; attributes, <span class="built_in">double</span> rotateAngle = <span class="number">0.0</span>, <span class="built_in">double</span> scaleFactor = <span class="number">1.0</span>, <span class="built_in">string</span> layoutName = <span class="string">&quot;&quot;</span></span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Database db = doc.Database;</span><br><span class="line">    ObjectId backObjectId = ObjectId.Null;</span><br><span class="line">    <span class="keyword">using</span> (<span class="keyword">var</span> docLock = doc.LockDocument())</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">using</span> (Transaction transaction = db.TransactionManager.StartTransaction())</span><br><span class="line">        &#123;</span><br><span class="line">            BlockTable bt = transaction.GetObject(db.BlockTableId, OpenMode.ForRead) <span class="keyword">as</span> BlockTable;</span><br><span class="line"></span><br><span class="line">            BlockTableRecord modelSpace = <span class="literal">null</span>;</span><br><span class="line">            ObjectId objectId = ObjectId.Null;</span><br><span class="line"></span><br><span class="line">            <span class="keyword">if</span> (!<span class="built_in">string</span>.IsNullOrWhiteSpace(layoutName))</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">var</span> layoutId = db.GetLayoutIdByName(layoutName);</span><br><span class="line">                <span class="keyword">if</span> (layoutId != ObjectId.Null)</span><br><span class="line">                    objectId = layoutId;</span><br><span class="line">                <span class="keyword">else</span></span><br><span class="line">                    <span class="keyword">return</span> backObjectId;</span><br><span class="line">            &#125;</span><br><span class="line">            <span class="keyword">else</span></span><br><span class="line">                objectId = bt[BlockTableRecord.ModelSpace];</span><br><span class="line">            modelSpace = transaction.GetObject(objectId, OpenMode.ForWrite) <span class="keyword">as</span> BlockTableRecord;</span><br><span class="line"></span><br><span class="line">            <span class="keyword">if</span> (bt.Has(blockName))</span><br><span class="line">            &#123;</span><br><span class="line">                BlockTableRecord btr = transaction.GetObject(bt[blockName], OpenMode.ForRead) <span class="keyword">as</span> BlockTableRecord;</span><br><span class="line">                BlockReference blockReference = <span class="keyword">new</span> BlockReference(insertPoint, bt[blockName]);</span><br><span class="line">                LayerTable layerTable = transaction.GetObject(db.LayerTableId, OpenMode.ForRead) <span class="keyword">as</span> LayerTable;</span><br><span class="line"></span><br><span class="line">                <span class="keyword">if</span> (layerTable.Has(layerName))</span><br><span class="line">                    blockReference.Layer = layerName;</span><br><span class="line">                <span class="keyword">else</span></span><br><span class="line">                    blockReference.Layer = <span class="string">&quot;0&quot;</span>;</span><br><span class="line"></span><br><span class="line">                blockReference.Rotation = rotateAngle;</span><br><span class="line">                blockReference.ScaleFactors = <span class="keyword">new</span> Scale3d(scaleFactor);</span><br><span class="line"></span><br><span class="line">                backObjectId = modelSpace.AppendEntity(blockReference);</span><br><span class="line"></span><br><span class="line">                <span class="keyword">if</span> (btr.HasAttributeDefinitions)</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="keyword">foreach</span> (ObjectId id <span class="keyword">in</span> btr)</span><br><span class="line">                    &#123;</span><br><span class="line">                        DBObject obj = id.GetObject(OpenMode.ForWrite);</span><br><span class="line">                        <span class="keyword">if</span> (obj <span class="keyword">is</span> AttributeDefinition)</span><br><span class="line">                        &#123;</span><br><span class="line">                            AttributeReference attrRef = <span class="keyword">new</span> AttributeReference();</span><br><span class="line">                            attrRef.SetAttributeFromBlock((AttributeDefinition)obj, blockReference.BlockTransform);</span><br><span class="line">                            <span class="keyword">if</span> (attributes.ContainsKey(attrRef.Tag.ToString()))</span><br><span class="line">                            &#123;</span><br><span class="line">                                <span class="keyword">var</span> <span class="keyword">value</span> = attributes[attrRef.Tag.ToString()];</span><br><span class="line">                                <span class="keyword">if</span> (<span class="keyword">value</span> == <span class="literal">null</span>)</span><br><span class="line">                                    <span class="keyword">value</span> = <span class="string">&quot;&quot;</span>;</span><br><span class="line">                                attrRef.TextString = <span class="keyword">value</span>;</span><br><span class="line">                                blockReference.AttributeCollection.AppendAttribute(attrRef);</span><br><span class="line">                                transaction.AddNewlyCreatedDBObject(attrRef, <span class="literal">true</span>);</span><br><span class="line">                            &#125;</span><br><span class="line">                        &#125;</span><br><span class="line">                    &#125;</span><br><span class="line">                &#125;</span><br><span class="line">                transaction.AddNewlyCreatedDBObject(blockReference, <span class="literal">true</span>);</span><br><span class="line">            &#125;</span><br><span class="line">            transaction.Commit();</span><br><span class="line">            <span class="keyword">return</span> backObjectId;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">ChangeBlockAttributes</span>(<span class="params"><span class="keyword">this</span> Document doc, BlockReference blockReference, Dictionary&lt;<span class="built_in">string</span>, <span class="built_in">string</span>&gt; attributes</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">if</span> (blockReference == <span class="literal">null</span> || attributes == <span class="literal">null</span> || attributes.Count == <span class="number">0</span>)</span><br><span class="line">        <span class="keyword">return</span>;</span><br><span class="line">    <span class="keyword">var</span> attrs = blockReference.AttributeCollection;</span><br><span class="line">    <span class="keyword">if</span> (attrs.Count == <span class="number">0</span>) <span class="keyword">return</span>;</span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = doc.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">foreach</span> (<span class="keyword">var</span> attr <span class="keyword">in</span> attrs)</span><br><span class="line">        &#123;</span><br><span class="line">            AttributeReference attrRef = <span class="literal">null</span>;</span><br><span class="line">            <span class="keyword">if</span> (attr <span class="keyword">is</span> ObjectId)</span><br><span class="line">                attrRef = transaction.GetObject((ObjectId)attr, OpenMode.ForWrite) <span class="keyword">as</span> AttributeReference;</span><br><span class="line">            <span class="keyword">else</span> <span class="keyword">if</span> (attr <span class="keyword">is</span> AttributeReference)</span><br><span class="line">                attrRef = attr <span class="keyword">as</span> AttributeReference;</span><br><span class="line">            <span class="keyword">if</span> (attrRef != <span class="literal">null</span> &amp;&amp; attributes.ContainsKey(attrRef.Tag.ToString()))</span><br><span class="line">                attrRef.TextString = attributes[attrRef.Tag.ToString()];</span><br><span class="line">        &#125;</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">ChangeBlockAttributesColor</span>(<span class="params"><span class="keyword">this</span> Document doc, BlockReference blockReference, <span class="built_in">int</span> colorIndex</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">if</span> (doc == <span class="literal">null</span> || blockReference == <span class="literal">null</span>) <span class="keyword">return</span>;</span><br><span class="line">    <span class="keyword">var</span> attrs = blockReference.AttributeCollection;</span><br><span class="line">    <span class="keyword">if</span> (attrs.Count == <span class="number">0</span>) <span class="keyword">return</span>;</span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = doc.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">foreach</span> (<span class="keyword">var</span> attr <span class="keyword">in</span> attrs)</span><br><span class="line">        &#123;</span><br><span class="line">            AttributeReference attrRef = <span class="literal">null</span>;</span><br><span class="line">            <span class="keyword">if</span> (attr <span class="keyword">is</span> ObjectId)</span><br><span class="line">                attrRef = transaction.GetObject((ObjectId)attr, OpenMode.ForWrite) <span class="keyword">as</span> AttributeReference;</span><br><span class="line">            <span class="keyword">else</span> <span class="keyword">if</span> (attr <span class="keyword">is</span> AttributeReference)</span><br><span class="line">                attrRef = attr <span class="keyword">as</span> AttributeReference;</span><br><span class="line">            <span class="keyword">if</span> (attrRef != <span class="literal">null</span>)</span><br><span class="line">                attrRef.ColorIndex = colorIndex;</span><br><span class="line">        &#125;</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
</div><!--!--></article></div><!--!--><nav class="post-navigation mt-4 level is-mobile"><div class="level-start"><a class="article-nav-prev level level-item link-muted" href="/post/4555870c9ae9/"><i class="level-item fas fa-chevron-left"></i><span class="level-item">实体颜色修改</span></a></div><div class="level-end"><a class="article-nav-next level level-item link-muted" href="/post/89ed5af22533/"><span class="level-item">文档操作</span><i class="level-item fas fa-chevron-right"></i></a></div></nav><div class="card"><div class="card-content"><h3 class="title is-5">评论</h3><div class="content" id="valine-thread"></div><script src="//cdn.jsdelivr.net/npm/leancloud-storage@3/dist/av-min.js"></script><script src="https://cdn.jsdelivr.net/npm/valine@1.4.16/dist/Valine.min.js"></script><script>new Valine({
            el: '#valine-thread',
            appId: "xIgb0xqNecOFPIzEcSTtTex2-gzGzoHsz",
            appKey: "DTvlJfXshQVAEzKL4tilxk0e",
            placeholder: "技术交流，思想碰撞，共同进步...",
            avatar: "hide",
            avatarForce: false,
            meta: ["nick","mail"],
            pageSize: 10,
            lang: "zh-CN",
            visitor: false,
            highlight: false,
            recordIP: false,
            
            
            
            enableQQ: false,
            requiredFields: [],
        });</script></div></div></div><!--!--><div class="column column-right is-4-tablet is-4-desktop is-3-widescreen  order-3 is-sticky"><div class="card widget" id="toc" data-type="toc"><div class="card-content"><div class="menu"><h3 class="menu-label">目录</h3><ul class="menu-list"><li><a class="level is-mobile" href="#普通块"><span class="level-left"><span class="level-item">1</span><span class="level-item"> 普通块</span></span></a></li><li><a class="level is-mobile" href="#动态属性块"><span class="level-left"><span class="level-item">2</span><span class="level-item"> 动态属性块</span></span></a></li><li><a class="level is-mobile" href="#增强属性块"><span class="level-left"><span class="level-item">3</span><span class="level-item"> 增强属性块</span></span></a></li></ul></div></div><script src="/js/toc.js" defer></script></div><div class="card widget" data-type="categories"><div class="card-content"><div class="menu"><h3 class="menu-label">分类</h3><ul class="menu-list"><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/"><span class="level-start"><span class="level-item">【工程】</span></span><span class="level-end"><span class="level-item tag">34</span></span></a><ul><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/C-C-%E6%B7%B7%E5%90%88%E7%BC%96%E7%A8%8B/"><span class="level-start"><span class="level-item">C++/C#混合编程</span></span><span class="level-end"><span class="level-item tag">5</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/C-C/"><span class="level-start"><span class="level-item">C/C++</span></span><span class="level-end"><span class="level-item tag">2</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/CAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91/"><span class="level-start"><span class="level-item">CAD二次开发</span></span><span class="level-end"><span class="level-item tag">13</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/MFC/"><span class="level-start"><span class="level-item">MFC</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/NET-C/"><span class="level-start"><span class="level-item">NET/C#</span></span><span class="level-end"><span class="level-item tag">2</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/WPF/"><span class="level-start"><span class="level-item">WPF</span></span><span class="level-end"><span class="level-item tag">7</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/wxWidgets/"><span class="level-start"><span class="level-item">wxWidgets</span></span><span class="level-end"><span class="level-item tag">2</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/%E5%AE%9E%E7%94%A8%E5%B7%A5%E5%85%B7/"><span class="level-start"><span class="level-item">实用工具</span></span><span class="level-end"><span class="level-item tag">2</span></span></a></li></ul></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%BA%95%E5%B1%82%E3%80%91/"><span class="level-start"><span class="level-item">【底层】</span></span><span class="level-end"><span class="level-item tag">2</span></span></a><ul><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%BA%95%E5%B1%82%E3%80%91/Windows%E7%B3%BB%E7%BB%9F%E7%BC%96%E7%A8%8B/"><span class="level-start"><span class="level-item">Windows系统编程</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%BA%95%E5%B1%82%E3%80%91/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/"><span class="level-start"><span class="level-item">计算机网络</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li></ul></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E6%9E%B6%E6%9E%84%E3%80%91/"><span class="level-start"><span class="level-item">【架构】</span></span><span class="level-end"><span class="level-item tag">6</span></span></a><ul><li><a class="level is-mobile" href="/categories/%E3%80%90%E6%9E%B6%E6%9E%84%E3%80%91/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/"><span class="level-start"><span class="level-item">设计模式</span></span><span class="level-end"><span class="level-item tag">5</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E6%9E%B6%E6%9E%84%E3%80%91/%E8%BD%AF%E4%BB%B6%E8%AE%BE%E8%AE%A1/"><span class="level-start"><span class="level-item">软件设计</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li></ul></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E7%AE%97%E6%B3%95%E3%80%91/"><span class="level-start"><span class="level-item">【算法】</span></span><span class="level-end"><span class="level-item tag">2</span></span></a><ul><li><a class="level is-mobile" href="/categories/%E3%80%90%E7%AE%97%E6%B3%95%E3%80%91/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95/"><span class="level-start"><span class="level-item">数据结构与算法</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E7%AE%97%E6%B3%95%E3%80%91/%E8%AE%A1%E7%AE%97%E5%87%A0%E4%BD%95/"><span class="level-start"><span class="level-item">计算几何</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li></ul></li><li><a class="level is-mobile" href="/categories/%E9%9A%8F%E7%AC%94/"><span class="level-start"><span class="level-item">随笔</span></span><span class="level-end"><span class="level-item tag">6</span></span></a></li></ul></div></div></div></div></div></div></section><footer class="footer"><div class="container"><div class="level"><div class="level-start"><a class="footer-logo is-block mb-2" href="/"><img src="/img/logo.svg" alt="李浩的博客" height="28"></a><p class="is-size-7"><span>李浩的博客 &copy; 2024 李浩</span> | Powered by <a href="https://hexo.io/" target="_blank" rel="noopener">Hexo</a> | Based on <a href="https://github.com/ppoffice/hexo-theme-icarus" target="_blank" rel="noopener">Icarus</a> theme</p><p class="is-size-7"><p class="is-size-7"><a href="https://beian.miit.gov.cn/" target="_blank">鄂ICP备2024055925号</a>&nbsp;|&nbsp;<a target="_blank" rel="noopener" href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral"><img src="/images/又拍云_logo2.png" width="45px" />提供加速服务</a></p></p><p class="is-size-7"><span id="busuanzi_container_site_uv">共<span id="busuanzi_value_site_uv">0</span>个访客</span></p></div><div class="level-end"></div></div></div></footer><script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/min/moment-with-locales.min.js"></script><script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.4/dist/clipboard.min.js" defer></script><script>moment.locale("zh-cn");</script><script>var IcarusThemeSettings = {
            article: {
                highlight: {
                    clipboard: true,
                    fold: 'unfolded'
                }
            }
        };</script><script src="/js/column.js"></script><script src="/js/animation.js"></script><a id="back-to-top" title="回到顶端" href="javascript:;"><i class="fas fa-chevron-up"></i></a><script src="/js/back_to_top.js" defer></script><!--!--><!--!--><!--!--><!--!--><script src="https://cdn.jsdelivr.net/npm/cookieconsent@3.1.1/build/cookieconsent.min.js" defer></script><script>window.addEventListener("load", () => {
      window.cookieconsent.initialise({
        type: "info",
        theme: "edgeless",
        static: false,
        position: "bottom-left",
        content: {
          message: "此网站使用Cookie来改善您的体验。",
          dismiss: "知道了！",
          allow: "允许使用Cookie",
          deny: "拒绝",
          link: "了解更多",
          policy: "Cookie政策",
          href: "https://www.cookiesandyou.com/",
        },
        palette: {
          popup: {
            background: "#edeff5",
            text: "#838391"
          },
          button: {
            background: "#4b81e8"
          },
        },
      });
    });</script><script src="https://cdn.jsdelivr.net/npm/lightgallery@1.10.0/dist/js/lightgallery.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/justifiedGallery@3.8.1/dist/js/jquery.justifiedGallery.min.js" defer></script><script>window.addEventListener("load", () => {
            if (typeof $.fn.lightGallery === 'function') {
                $('.article').lightGallery({ selector: '.gallery-item' });
            }
            if (typeof $.fn.justifiedGallery === 'function') {
                if ($('.justified-gallery > p > .gallery-item').length) {
                    $('.justified-gallery > p > .gallery-item').unwrap();
                }
                $('.justified-gallery').justifiedGallery();
            }
        });</script><!--!--><!--!--><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css"><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/contrib/auto-render.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/contrib/mhchem.min.js" defer></script><script>window.addEventListener("load", function() {
            document.querySelectorAll('[role="article"] > .content').forEach(function(element) {
                renderMathInElement(element);
            });
        });</script><!--!--><!--!--><!--!--><script src="/js/main.js" defer></script><div class="searchbox"><div class="searchbox-container"><div class="searchbox-header"><div class="searchbox-input-container"><input class="searchbox-input" type="text" placeholder="想要查找什么..."></div><a class="searchbox-close" href="javascript:;">×</a></div><div class="searchbox-body"></div></div></div><script src="/js/insight.js" defer></script><script>document.addEventListener('DOMContentLoaded', function () {
            loadInsight({"contentUrl":"/content.json"}, {"hint":"想要查找什么...","untitled":"(无标题)","posts":"文章","pages":"页面","categories":"分类","tags":"标签"});
        });</script></body></html>