<!doctype html>
<html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"><meta><title>布局和视口 - 李浩的博客</title><link rel="manifest" href="/manifest.json"><meta name="application-name" content="李浩"><meta name="msapplication-TileImage" content="/img/favicon.svg"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="李浩"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="description" content="布局和视口是CAD出图的重要手段之一，其中视口可以映射到模型空间的任一范围，进而在布局空间灵活组织图形成果。 本文针对布局创建及切换、视口创建封装若干接口。"><meta property="og:type" content="blog"><meta property="og:title" content="布局和视口"><meta property="og:url" content="http://example.com/post/f3a8f2326720/"><meta property="og:site_name" content="李浩的博客"><meta property="og:description" content="布局和视口是CAD出图的重要手段之一，其中视口可以映射到模型空间的任一范围，进而在布局空间灵活组织图形成果。 本文针对布局创建及切换、视口创建封装若干接口。"><meta property="og:locale" content="zh_CN"><meta property="og:image" content="http://example.com/img/og_image.png"><meta property="article:published_time" content="2024-07-07T08:03:46.000Z"><meta property="article:modified_time" content="2024-07-07T13:17:03.635Z"><meta property="article:author" content="李浩"><meta property="twitter:card" content="summary"><meta property="twitter:image:src" content="http://example.com/img/og_image.png"><script type="application/ld+json">{"@context":"https://schema.org","@type":"BlogPosting","mainEntityOfPage":{"@type":"WebPage","@id":"http://example.com/post/f3a8f2326720/"},"headline":"布局和视口","image":["http://example.com/img/og_image.png"],"datePublished":"2024-07-07T08:03:46.000Z","dateModified":"2024-07-07T13:17:03.635Z","author":{"@type":"Person","name":"李浩"},"publisher":{"@type":"Organization","name":"李浩的博客","logo":{"@type":"ImageObject","url":"http://example.com/img/logo.svg"}},"description":"布局和视口是CAD出图的重要手段之一，其中视口可以映射到模型空间的任一范围，进而在布局空间灵活组织图形成果。 本文针对布局创建及切换、视口创建封装若干接口。"}</script><link rel="canonical" href="http://example.com/post/f3a8f2326720/"><link rel="icon" href="/img/favicon.svg"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@11.7.0/styles/github.css"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;600&amp;family=Source+Code+Pro"><link rel="stylesheet" href="/css/default.css"><style>body>.footer,body>.navbar,body>.section{opacity:0}</style><!--!--><!--!--><!--!--><script src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js" defer></script><!--!--><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cookieconsent@3.1.1/build/cookieconsent.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lightgallery@1.10.0/dist/css/lightgallery.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/justifiedGallery@3.8.1/dist/css/justifiedGallery.min.css"><!--!--><!--!--><!--!--><style>.pace{-webkit-pointer-events:none;pointer-events:none;-webkit-user-select:none;-moz-user-select:none;user-select:none}.pace-inactive{display:none}.pace .pace-progress{background:#3273dc;position:fixed;z-index:2000;top:0;right:100%;width:100%;height:2px}</style><script src="https://cdn.jsdelivr.net/npm/pace-js@1.2.4/pace.min.js"></script><!--!--><!--!--><!-- hexo injector head_end start --><script>
  (function () {
      function switchTab() {
          if (!location.hash) {
            return;
          }

          const id = '#' + CSS.escape(location.hash.substring(1));
          const $tabMenu = document.querySelector(`.tabs a[href="${id}"]`);
          if (!$tabMenu) {
            return;
          }

          const $tabMenuContainer = $tabMenu.parentElement.parentElement;
          Array.from($tabMenuContainer.children).forEach($menu => $menu.classList.remove('is-active'));
          Array.from($tabMenuContainer.querySelectorAll('a'))
              .map($menu => document.getElementById($menu.getAttribute("href").substring(1)))
              .forEach($content => $content.classList.add('is-hidden'));

          if ($tabMenu) {
              $tabMenu.parentElement.classList.add('is-active');
          }
          const $activeTab = document.querySelector(id);
          if ($activeTab) {
              $activeTab.classList.remove('is-hidden');
          }
      }
      switchTab();
      window.addEventListener('hashchange', switchTab, false);
  })();
  </script><!-- hexo injector head_end end --><meta name="generator" content="Hexo 7.2.0"></head><body class="is-2-column"><nav class="navbar navbar-main"><div class="container navbar-container"><div class="navbar-brand justify-content-center"><a class="navbar-item navbar-logo" href="/"><img src="/img/logo.svg" alt="李浩的博客" height="28"></a></div><div class="navbar-menu"><div class="navbar-start"><a class="navbar-item" href="/">主页</a><a class="navbar-item" href="/categories">分类</a><a class="navbar-item" href="/categories/%E9%9A%8F%E7%AC%94">随笔</a><a class="navbar-item" href="/categories/%E3%80%90%E5%BA%95%E5%B1%82%E3%80%91">【底层】</a><a class="navbar-item" href="/categories/%E3%80%90%E7%AE%97%E6%B3%95%E3%80%91">【算法】</a><a class="navbar-item" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91">【工程】</a><a class="navbar-item" href="/categories/%E3%80%90%E6%9E%B6%E6%9E%84%E3%80%91">【架构】</a><a class="navbar-item" href="/link">链接</a><a class="navbar-item" href="/about">关于</a></div><div class="navbar-end"><a class="navbar-item is-hidden-tablet catalogue" title="目录" href="javascript:;"><i class="fas fa-list-ul"></i></a><a class="navbar-item search" title="搜索" href="javascript:;"><i class="fas fa-search"></i></a></div></div></div></nav><section class="section"><div class="container"><div class="columns"><div class="column order-2 column-main is-8-tablet is-9-desktop is-9-widescreen"><div class="card"><article class="card-content article" role="article"><div class="article-meta is-size-7 is-uppercase level is-mobile"><div class="level-left"><span class="level-item"><time dateTime="2024-07-07T08:03:46.000Z" title="2024/7/7 16:03:46">2024-07-07</time>发表</span><span class="level-item"><time dateTime="2024-07-07T13:17:03.635Z" title="2024/7/7 21:17:03">2024-07-07</time>更新</span><span class="level-item"><a class="link-muted" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/">【工程】</a><span> / </span><a class="link-muted" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/CAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91/">CAD二次开发</a></span><span class="level-item" id="busuanzi_container_page_pv"><span id="busuanzi_value_page_pv">0</span>次访问</span></div></div><h1 class="title is-3 is-size-4-mobile">布局和视口</h1><div class="content"><p>布局和视口是CAD出图的重要手段之一，其中视口可以映射到模型空间的任一范围，进而在布局空间灵活组织图形成果。<br>
本文针对布局创建及切换、视口创建封装若干接口。</p>
<span id="more"></span>
<h1 id="切换布局"><a class="markdownIt-Anchor" href="#切换布局"></a> 切换布局</h1>
<p>借助Database的TileMode属性来切换到模型空间</p>
<figure class="highlight cs"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">SwitchLayout</span>(<span class="params"><span class="keyword">this</span> Document doc, <span class="built_in">string</span> layoutName</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">if</span> (<span class="built_in">string</span>.IsNullOrWhiteSpace(layoutName) || ObjectId.Null == doc.Database.GetLayoutIdByName(layoutName)) </span><br><span class="line">        <span class="keyword">return</span>;</span><br><span class="line">    <span class="keyword">using</span> (<span class="keyword">var</span> docLock = doc.LockDocument())</span><br><span class="line">        LayoutManager.Current.CurrentLayout = layoutName;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">SwitchToModel</span>()</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">var</span> doc = DwgOperators.ThisDocument;</span><br><span class="line">    <span class="keyword">using</span> (<span class="keyword">var</span> docLock = doc.LockDocument())</span><br><span class="line">        doc.Database.TileMode = <span class="literal">true</span>;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">//----------------------------------------------------------------------</span></span><br><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">static</span> ObjectId <span class="title">GetLayoutIdByName</span>(<span class="params"><span class="keyword">this</span> Database db, <span class="built_in">string</span> layoutName</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ObjectId resId = ObjectId.Null;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (<span class="built_in">string</span>.IsNullOrWhiteSpace(layoutName))</span><br><span class="line">        <span class="keyword">return</span> resId;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = db.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        BlockTable blockTable = transaction.GetObject(db.BlockTableId, OpenMode.ForRead) <span class="keyword">as</span> BlockTable;</span><br><span class="line">        <span class="keyword">foreach</span> (ObjectId id <span class="keyword">in</span> blockTable)</span><br><span class="line">        &#123;</span><br><span class="line">            BlockTableRecord btr = transaction.GetObject(id, OpenMode.ForRead) <span class="keyword">as</span> BlockTableRecord;</span><br><span class="line">            <span class="keyword">if</span> (btr.IsLayout)</span><br><span class="line">            &#123;</span><br><span class="line">                Layout layout = transaction.GetObject(btr.LayoutId, OpenMode.ForRead) <span class="keyword">as</span> Layout;</span><br><span class="line">                <span class="keyword">if</span> (layout.LayoutName == layoutName)</span><br><span class="line">                &#123;</span><br><span class="line">                    resId = id;</span><br><span class="line">                    <span class="keyword">break</span>;</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> resId;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h1 id="创建布局"><a class="markdownIt-Anchor" href="#创建布局"></a> 创建布局</h1>
<p>为了使新布局生效，调用SwitchLayout()切换一下。</p>
<figure class="highlight cs"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> ObjectId <span class="title">CreateLayout</span>(<span class="params"><span class="keyword">this</span> Document doc, <span class="built_in">string</span> layoutName</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ObjectId resId = ObjectId.Null;</span><br><span class="line">    <span class="keyword">if</span> (doc == <span class="literal">null</span> || <span class="built_in">string</span>.IsNullOrWhiteSpace(layoutName))</span><br><span class="line">        <span class="keyword">return</span> resId;</span><br><span class="line">    <span class="keyword">var</span> db = doc.Database;</span><br><span class="line">    <span class="keyword">if</span> (db.GetLayoutIdByName(layoutName) != ObjectId.Null) </span><br><span class="line">        <span class="keyword">return</span> resId;</span><br><span class="line">    <span class="keyword">using</span> (<span class="keyword">var</span> docLock = doc.LockDocument())</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">using</span> (Transaction transaction = doc.TransactionManager.StartTransaction())</span><br><span class="line">        &#123;</span><br><span class="line">            DBDictionary layouts = transaction.GetObject(db.LayoutDictionaryId, OpenMode.ForWrite) <span class="keyword">as</span> DBDictionary;</span><br><span class="line">            resId = LayoutManager.Current.CreateLayout(layoutName);</span><br><span class="line">            transaction.Commit();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    doc.Database.SwitchLayout(layoutName);</span><br><span class="line">    <span class="keyword">return</span> resId;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h1 id="创建视口"><a class="markdownIt-Anchor" href="#创建视口"></a> 创建视口</h1>
<p>创建从任一矩形创建视口的函数，此函数的开发着实花费了不少精力，感叹一下！</p>
<ul>
<li>CreateViewportIntoPaperspace()：创建模型空间中任一矩形的视口（很实用）</li>
<li>SetViewportLockedLayers()：设置某一视口中的图层状态</li>
<li>AddUCS()：添加用户坐标系</li>
</ul>
<figure class="highlight cs"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br><span class="line">91</span><br><span class="line">92</span><br><span class="line">93</span><br><span class="line">94</span><br><span class="line">95</span><br><span class="line">96</span><br><span class="line">97</span><br><span class="line">98</span><br><span class="line">99</span><br><span class="line">100</span><br><span class="line">101</span><br><span class="line">102</span><br><span class="line">103</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> ObjectId <span class="title">CreateViewportIntoPaperspace</span>(<span class="params"><span class="keyword">this</span> Database db,<span class="built_in">string</span> layoutName, Point3d leftBottomPoint, <span class="built_in">double</span> width, <span class="built_in">double</span> height,<span class="built_in">double</span> rotation, Point3d viewportLeftBottomPoint, <span class="built_in">double</span>? viewportWidth = <span class="literal">null</span>,<span class="built_in">double</span>? viewportHeight = <span class="literal">null</span>, <span class="built_in">double</span> scale = <span class="number">1.0</span></span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ObjectId resId = ObjectId.Null;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (<span class="built_in">string</span>.IsNullOrWhiteSpace(layoutName))</span><br><span class="line">        <span class="keyword">return</span> resId;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = db.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        Viewport vport = <span class="keyword">new</span> Viewport();</span><br><span class="line">        </span><br><span class="line">        <span class="built_in">double</span> vWidth, vHeight;</span><br><span class="line">        <span class="keyword">if</span> (viewportWidth == <span class="literal">null</span>)</span><br><span class="line">            vWidth = width;</span><br><span class="line">        <span class="keyword">else</span></span><br><span class="line">            vWidth = viewportWidth.Value;</span><br><span class="line">        <span class="keyword">if</span> (viewportHeight == <span class="literal">null</span>)</span><br><span class="line">            vHeight = height;</span><br><span class="line">        <span class="keyword">else</span></span><br><span class="line">            vHeight = viewportHeight.Value;</span><br><span class="line">        vport.CenterPoint = <span class="keyword">new</span> Point3d(viewportLeftBottomPoint.X + <span class="number">0.5</span> * vWidth, viewportLeftBottomPoint.Y + <span class="number">0.5</span> * vHeight, <span class="number">0</span>);</span><br><span class="line">        vport.Width = vWidth;</span><br><span class="line">        vport.Height = vHeight;</span><br><span class="line">        </span><br><span class="line">        <span class="keyword">var</span> point = CoorTransform(leftBottomPoint, rotation, <span class="keyword">new</span> Point3d(<span class="number">0.5</span> * width, <span class="number">0.5</span> * height, <span class="number">0</span>));</span><br><span class="line">        vport.ViewTarget = point;</span><br><span class="line">        </span><br><span class="line">        <span class="keyword">var</span> ucsId = db.AddUCS(<span class="string">$&quot;ucs-<span class="subst">&#123;Guid.NewGuid().ToString()&#125;</span>&quot;</span>, leftBottomPoint,</span><br><span class="line">                              <span class="keyword">new</span> Vector3d(Math.Cos(rotation), Math.Sin(rotation), <span class="number">0</span>),</span><br><span class="line">                              <span class="keyword">new</span> Vector3d(Math.Cos(rotation + <span class="number">0.5</span> * Math.PI), Math.Sin(rotation + <span class="number">0.5</span> * Math.PI), <span class="number">0</span>));</span><br><span class="line">        vport.SetUcs(ucsId);</span><br><span class="line">        </span><br><span class="line">        vport.TwistAngle = Math.PI * <span class="number">2</span> - rotation;</span><br><span class="line">        vport.ViewDirection = <span class="keyword">new</span> Vector3d(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>);</span><br><span class="line">        vport.CustomScale = scale;</span><br><span class="line">        resId = db.AddEntity(vport, layoutName);</span><br><span class="line">        db.SwitchLayout(layoutName);</span><br><span class="line">        vport.On = <span class="literal">true</span>;</span><br><span class="line"></span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> resId;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">SetViewportLockedLayers</span>(<span class="params"><span class="keyword">this</span> Document doc, ObjectId id, List&lt;<span class="built_in">string</span>&gt; frozenLayerNames</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">if</span> (doc == <span class="literal">null</span> || id == ObjectId.Null) <span class="keyword">return</span>;</span><br><span class="line">    <span class="keyword">if</span> (frozenLayerNames == <span class="literal">null</span> || frozenLayerNames.Count == <span class="number">0</span>) <span class="keyword">return</span>;</span><br><span class="line">    <span class="keyword">var</span> db = doc.Database;</span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = db.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        Viewport vp = transaction.GetObject(id, OpenMode.ForWrite) <span class="keyword">as</span> Viewport;</span><br><span class="line">        <span class="keyword">if</span> (vp != <span class="literal">null</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            LayerTable lt = transaction.GetObject(db.LayerTableId, OpenMode.ForRead) <span class="keyword">as</span> LayerTable;</span><br><span class="line">            List&lt;ObjectId&gt; layerIds = <span class="keyword">new</span> List&lt;ObjectId&gt;();</span><br><span class="line">            <span class="keyword">foreach</span> (<span class="keyword">var</span> name <span class="keyword">in</span> frozenLayerNames)</span><br><span class="line">                <span class="keyword">if</span> (lt.Has(name))</span><br><span class="line">                    layerIds.Add(lt[name]);</span><br><span class="line">            vp.FreezeLayersInViewport(layerIds.GetEnumerator());</span><br><span class="line">        &#125;</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">//----------------------------------------------------------------------</span></span><br><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">static</span> ObjectId <span class="title">AddUCS</span>(<span class="params"><span class="keyword">this</span> Database db, <span class="built_in">string</span> ucsName, Point3d origin, Vector3d xAxis, Vector3d yAxis</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ObjectId resId = ObjectId.Null;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (<span class="built_in">string</span>.IsNullOrWhiteSpace(ucsName))</span><br><span class="line">        <span class="keyword">return</span> resId;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = db.TransactionManager.StartTransaction())</span><br><span class="line">    &#123;</span><br><span class="line">        UcsTable ucsTable = transaction.GetObject(db.UcsTableId, OpenMode.ForWrite) <span class="keyword">as</span> UcsTable;</span><br><span class="line">        <span class="keyword">if</span> (!ucsTable.Has(ucsName))</span><br><span class="line">        &#123;</span><br><span class="line">            UcsTableRecord ucsTableRecord = <span class="keyword">new</span> UcsTableRecord();</span><br><span class="line">            ucsTableRecord.Name = ucsName;</span><br><span class="line">            ucsTableRecord.Origin = origin;</span><br><span class="line">            ucsTableRecord.XAxis = xAxis;</span><br><span class="line">            ucsTableRecord.YAxis = yAxis;</span><br><span class="line"></span><br><span class="line">            resId = ucsTable.Add(ucsTableRecord);</span><br><span class="line">            transaction.AddNewlyCreatedDBObject(ucsTableRecord, <span class="literal">true</span>);</span><br><span class="line">            ucsTable.DowngradeOpen();</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">else</span></span><br><span class="line">            resId = ucsTable[ucsName];</span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> resId;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">static</span> Point3d <span class="title">CoorTransform</span>(<span class="params">Point3d deltaDist, <span class="built_in">double</span> rotation, Point3d p1</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="built_in">double</span> dist1 = Math.Sqrt(p1.X * p1.X + p1.Y * p1.Y);</span><br><span class="line">    <span class="built_in">double</span> rotation1 = Arctan(p1.Y, p1.X);</span><br><span class="line">    <span class="built_in">double</span> totalRotation = rotation1 + rotation;</span><br><span class="line">    Point3d resPoint = <span class="keyword">new</span> Point3d(deltaDist.X + dist1 * Math.Cos(totalRotation), deltaDist.Y + dist1 * Math.Sin(totalRotation), <span class="number">0</span>);</span><br><span class="line">    <span class="keyword">return</span> resPoint;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
</div><!--!--></article></div><!--!--><nav class="post-navigation mt-4 level is-mobile"><div class="level-start"><a class="article-nav-prev level level-item link-muted" href="/post/3f69b07ca04f/"><i class="level-item fas fa-chevron-left"></i><span class="level-item">扩展数据</span></a></div><div class="level-end"><a class="article-nav-next level level-item link-muted" href="/post/1b8b9c6eaa89/"><span class="level-item">图形变换</span><i class="level-item fas fa-chevron-right"></i></a></div></nav><div class="card"><div class="card-content"><h3 class="title is-5">评论</h3><div class="content" id="valine-thread"></div><script src="//cdn.jsdelivr.net/npm/leancloud-storage@3/dist/av-min.js"></script><script src="https://cdn.jsdelivr.net/npm/valine@1.4.16/dist/Valine.min.js"></script><script>new Valine({
            el: '#valine-thread',
            appId: "xIgb0xqNecOFPIzEcSTtTex2-gzGzoHsz",
            appKey: "DTvlJfXshQVAEzKL4tilxk0e",
            placeholder: "技术交流，思想碰撞，共同进步...",
            avatar: "hide",
            avatarForce: false,
            meta: ["nick","mail"],
            pageSize: 10,
            lang: "zh-CN",
            visitor: false,
            highlight: false,
            recordIP: false,
            
            
            
            enableQQ: false,
            requiredFields: [],
        });</script></div></div></div><!--!--><div class="column column-right is-4-tablet is-4-desktop is-3-widescreen  order-3 is-sticky"><div class="card widget" id="toc" data-type="toc"><div class="card-content"><div class="menu"><h3 class="menu-label">目录</h3><ul class="menu-list"><li><a class="level is-mobile" href="#切换布局"><span class="level-left"><span class="level-item">1</span><span class="level-item"> 切换布局</span></span></a></li><li><a class="level is-mobile" href="#创建布局"><span class="level-left"><span class="level-item">2</span><span class="level-item"> 创建布局</span></span></a></li><li><a class="level is-mobile" href="#创建视口"><span class="level-left"><span class="level-item">3</span><span class="level-item"> 创建视口</span></span></a></li></ul></div></div><script src="/js/toc.js" defer></script></div><div class="card widget" data-type="categories"><div class="card-content"><div class="menu"><h3 class="menu-label">分类</h3><ul class="menu-list"><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/"><span class="level-start"><span class="level-item">【工程】</span></span><span class="level-end"><span class="level-item tag">33</span></span></a><ul><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/C-C-%E6%B7%B7%E5%90%88%E7%BC%96%E7%A8%8B/"><span class="level-start"><span class="level-item">C++/C#混合编程</span></span><span class="level-end"><span class="level-item tag">5</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/C-C/"><span class="level-start"><span class="level-item">C/C++</span></span><span class="level-end"><span class="level-item tag">2</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/CAD%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91/"><span class="level-start"><span class="level-item">CAD二次开发</span></span><span class="level-end"><span class="level-item tag">13</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/NET-C/"><span class="level-start"><span class="level-item">NET/C#</span></span><span class="level-end"><span class="level-item tag">2</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/WPF/"><span class="level-start"><span class="level-item">WPF</span></span><span class="level-end"><span class="level-item tag">7</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/wxWidgets/"><span class="level-start"><span class="level-item">wxWidgets</span></span><span class="level-end"><span class="level-item tag">2</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%B7%A5%E7%A8%8B%E3%80%91/%E5%AE%9E%E7%94%A8%E5%B7%A5%E5%85%B7/"><span class="level-start"><span class="level-item">实用工具</span></span><span class="level-end"><span class="level-item tag">2</span></span></a></li></ul></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%BA%95%E5%B1%82%E3%80%91/"><span class="level-start"><span class="level-item">【底层】</span></span><span class="level-end"><span class="level-item tag">2</span></span></a><ul><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%BA%95%E5%B1%82%E3%80%91/Windows%E7%B3%BB%E7%BB%9F%E7%BC%96%E7%A8%8B/"><span class="level-start"><span class="level-item">Windows系统编程</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E5%BA%95%E5%B1%82%E3%80%91/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/"><span class="level-start"><span class="level-item">计算机网络</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li></ul></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E6%9E%B6%E6%9E%84%E3%80%91/"><span class="level-start"><span class="level-item">【架构】</span></span><span class="level-end"><span class="level-item tag">6</span></span></a><ul><li><a class="level is-mobile" href="/categories/%E3%80%90%E6%9E%B6%E6%9E%84%E3%80%91/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/"><span class="level-start"><span class="level-item">设计模式</span></span><span class="level-end"><span class="level-item tag">5</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E6%9E%B6%E6%9E%84%E3%80%91/%E8%BD%AF%E4%BB%B6%E8%AE%BE%E8%AE%A1/"><span class="level-start"><span class="level-item">软件设计</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li></ul></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E7%AE%97%E6%B3%95%E3%80%91/"><span class="level-start"><span class="level-item">【算法】</span></span><span class="level-end"><span class="level-item tag">2</span></span></a><ul><li><a class="level is-mobile" href="/categories/%E3%80%90%E7%AE%97%E6%B3%95%E3%80%91/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95/"><span class="level-start"><span class="level-item">数据结构与算法</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li><li><a class="level is-mobile" href="/categories/%E3%80%90%E7%AE%97%E6%B3%95%E3%80%91/%E8%AE%A1%E7%AE%97%E5%87%A0%E4%BD%95/"><span class="level-start"><span class="level-item">计算几何</span></span><span class="level-end"><span class="level-item tag">1</span></span></a></li></ul></li><li><a class="level is-mobile" href="/categories/%E9%9A%8F%E7%AC%94/"><span class="level-start"><span class="level-item">随笔</span></span><span class="level-end"><span class="level-item tag">6</span></span></a></li></ul></div></div></div></div></div></div></section><footer class="footer"><div class="container"><div class="level"><div class="level-start"><a class="footer-logo is-block mb-2" href="/"><img src="/img/logo.svg" alt="李浩的博客" height="28"></a><p class="is-size-7"><span>李浩的博客 &copy; 2024 李浩</span> | Powered by <a href="https://hexo.io/" target="_blank" rel="noopener">Hexo</a> | Based on <a href="https://github.com/ppoffice/hexo-theme-icarus" target="_blank" rel="noopener">Icarus</a> theme</p><p class="is-size-7"><p class="is-size-7"><a href="https://beian.miit.gov.cn/" target="_blank">鄂ICP备2024055925号</a>&nbsp;|&nbsp;<a target="_blank" rel="noopener" href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral"><img src="/images/又拍云_logo2.png" width="45px" />提供加速服务</a></p></p><p class="is-size-7"><span id="busuanzi_container_site_uv">共<span id="busuanzi_value_site_uv">0</span>个访客</span></p></div><div class="level-end"></div></div></div></footer><script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/min/moment-with-locales.min.js"></script><script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.4/dist/clipboard.min.js" defer></script><script>moment.locale("zh-cn");</script><script>var IcarusThemeSettings = {
            article: {
                highlight: {
                    clipboard: true,
                    fold: 'unfolded'
                }
            }
        };</script><script src="/js/column.js"></script><script src="/js/animation.js"></script><a id="back-to-top" title="回到顶端" href="javascript:;"><i class="fas fa-chevron-up"></i></a><script src="/js/back_to_top.js" defer></script><!--!--><!--!--><!--!--><!--!--><script src="https://cdn.jsdelivr.net/npm/cookieconsent@3.1.1/build/cookieconsent.min.js" defer></script><script>window.addEventListener("load", () => {
      window.cookieconsent.initialise({
        type: "info",
        theme: "edgeless",
        static: false,
        position: "bottom-left",
        content: {
          message: "此网站使用Cookie来改善您的体验。",
          dismiss: "知道了！",
          allow: "允许使用Cookie",
          deny: "拒绝",
          link: "了解更多",
          policy: "Cookie政策",
          href: "https://www.cookiesandyou.com/",
        },
        palette: {
          popup: {
            background: "#edeff5",
            text: "#838391"
          },
          button: {
            background: "#4b81e8"
          },
        },
      });
    });</script><script src="https://cdn.jsdelivr.net/npm/lightgallery@1.10.0/dist/js/lightgallery.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/justifiedGallery@3.8.1/dist/js/jquery.justifiedGallery.min.js" defer></script><script>window.addEventListener("load", () => {
            if (typeof $.fn.lightGallery === 'function') {
                $('.article').lightGallery({ selector: '.gallery-item' });
            }
            if (typeof $.fn.justifiedGallery === 'function') {
                if ($('.justified-gallery > p > .gallery-item').length) {
                    $('.justified-gallery > p > .gallery-item').unwrap();
                }
                $('.justified-gallery').justifiedGallery();
            }
        });</script><!--!--><!--!--><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css"><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/contrib/auto-render.min.js" defer></script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/contrib/mhchem.min.js" defer></script><script>window.addEventListener("load", function() {
            document.querySelectorAll('[role="article"] > .content').forEach(function(element) {
                renderMathInElement(element);
            });
        });</script><!--!--><!--!--><!--!--><script src="/js/main.js" defer></script><div class="searchbox"><div class="searchbox-container"><div class="searchbox-header"><div class="searchbox-input-container"><input class="searchbox-input" type="text" placeholder="想要查找什么..."></div><a class="searchbox-close" href="javascript:;">×</a></div><div class="searchbox-body"></div></div></div><script src="/js/insight.js" defer></script><script>document.addEventListener('DOMContentLoaded', function () {
            loadInsight({"contentUrl":"/content.json"}, {"hint":"想要查找什么...","untitled":"(无标题)","posts":"文章","pages":"页面","categories":"分类","tags":"标签"});
        });</script></body></html>